#!/usr/bin/env ruby
require 'net/http'
message_file = ARGV[0]
message = File.read(message_file)
$hoursRegex = /\[hours: (\d+)\]/
if !$hoursRegex.match(message)
    puts "[HENRY] Your commit mesage is missing the hours field, commit aborted"
    exit 1
end

hours = message[$hoursRegex,1]

port = 8080
host = '127.0.0.1'
path = '/commit?hours='+hours
req = Net::HTTP::Put.new(path, initheader = {'Content-Type' => 'text/plain'}}
req.body = ''
response = Net::HTTP.new(host, port).start {|http| http.request(req)}
puts response.code
