#!/usr/bin/python
import sys
import re
import subprocess
import time
from firebase import firebase


##
#   These fields are populated by the initializer
##
projectID = '-JYcg488tAYS5rJJT4Kh'
githubID = 'aj-michael'

prodUrl = 'https://henry-production.firebaseio.com'
stagUrl = 'https://henry-staging.firebaseio.com'
testUrl = 'https://henry-test.firebaseio.com'


def readCommit(path):
    with open(path,'r') as msgfile:
        msg = msgfile.read()
    return msg.strip()
    

def getLoC():
    command = 'git diff --cached --shortstat'.split(' ')
    pipe = subprocess.Popen(command,stdout=subprocess.PIPE)
    pair = pipe.communicate()[0]
    vals = pair.replace(' ','').split(',') 
    if len(vals) == 3:
        vals = vals[1:]
    elif len(vals) == 2:
        vals = [vals[1]]+['0'] if 'insertion' in pair else ['0']+[vals[1]]
    elif len(vals) == 1:
        raise Exception('HENRY: Unexpected output of `git diff --cached --shortstat`')
    else:
        vals = ['0','0']
    nums = map(lambda x: int(x[0]),vals) 
    return nums[0] - nums[1]


def parse(msg):
    hoursRE = r"\[hours:([0-9]+)\]"
    milestoneRE = r"\[milestone:([0-9]+)\]"
    taskRE = r"\[task:([0-9]+)\]"
    statusRE = r"\[status:([0-9]+)\]"

    rexs = [hoursRE,milestoneRE,taskRE,statusRE]
    results = [re.search(rex,msg) for rex in rexs]
    results = [res.group(1) if res != None else None for res in results]
    return results


def getEmail():
    command = 'git config --global user.email'.split(' ')
    pipe = subprocess.Popen(command,stdout=subprocess.PIPE)
    return pipe.communicate()[0].strip()
    

def getUserID(gituser,ref):
    users = ref.get('/users',None)
    filteredusers = {u:users[u] for u in users if 'github' in users[u]}
    try:
        userID = [u for u in filteredusers if filteredusers[u]['github']==gituser][0]
    except:
        raise Exception('HENRY: Invalid username, commit failed')
    return userID


def getTime():
    return int(time.time()*1000)

def getMilestoneID(projectID,milestone):
    pass


def getTaskID(projectID,milestone,task):
    pass


def writeCommit(ref,msg,project,uid,hours,milestone,task,status,loc,ts):
    path = '/commits'
    try:
        result = ref.post(path,{'hours':hours,'user':uid,'lines_of_code':loc,'message':msg,'timestamp':ts})
    except:
        raise Exception('Connection to Firebase commits table denied')
    return result.values()[0]


def addCommitToUser(ref,uid,commitid):
    path = '/users/' + uid + '/commits'
    try:
        ref.patch(path,{commitid:commitid})
    except:
        raise Exception('Connection to Firebase users table denied')


def addCommitToProject(ref,projectid,commitid):
    path = '/projects/'+projectid+'/commits'
    try:
        ref.patch(path,{commitid:commitid})
    except:
        raise Exception('Connection to Firebase projects table denied')
    
def promptAsNecessary(hours,milestone,task,status):
    sys.stdin = open('/dev/tty')
    if hours == None:
        hours = raw_input('Hours: ')
    if milestone == None:
        milestone = raw_input('Milestone: ')
    if task == None:
        task = raw_input('Task: ')
    if status == None:
        status = raw_input('Status: ')
    return hours,milestone,task,status


if __name__ == '__main__':
    # set this to the correct database
    ref = firebase.FirebaseApplication(testUrl, None)

    email = getEmail()
    userID = getUserID(githubID,ref)
    msg = readCommit(sys.argv[1])
    [hours,milestone,task,status],loc = parse(msg),getLoC()
    ts = getTime()
    hours,milestone,task,status = promptAsNecessary(hours,milestone,task,status)

    taskID = getTaskID(projectID,milestone,task)

    commitID = writeCommit(ref,msg,None,userID,int(hours),milestone,task,status,loc,ts)

    addCommitToProject(ref,projectID,commitID)
    addCommitToUser(ref,userID,commitID)
    
    raise Exception('Reached end, prevents commit from executing')
