#!/usr/bin/python
import sys
import re
from firebase import firebase

#firebaseUrl = 'https://henry371.firebaseio.com'
firebaseUrl = 'https://henry372.firebaseio.com'
firebase = firebase.FirebaseApplication(firebaseUrl, None)

#sys.argv[0] is the path to this file
#sys.argv[1] is the path to commit file
with open(sys.argv[1], "r") as msgfile:
    msg = msgfile.read()

hoursRE = r"\[hours: ([0-9]+)\]"


hours = re.search(hoursRE, msg)

# no hour included
if hours == None:
    print "Hours not included, set to zero by default"
    hours = 0
else:
    hours = hours.group(1)

print "Hours were: " + str(hours)



#print firebase.get('/user', None)
path = '/users'
key = 'Sample user'
value = 'Sample field'
firebase.put(path, key, value)

