#!/usr/bin/python
import requests
import json
from base64 import b64decode
import os

gh_url = 'https://api.github.com/repos/aj-michael/Henry/contents/commit-msg'
hook_dir = os.getcwd()+'/.git/hooks'
hook_path = os.getcwd()+'/.git/hooks/commit-msg'

try:
    with open(hook_path,'w') as f:
        pass
except IOError:
    print 'Error: Must be in the root of a Git repository'
    exit(1)

r = requests.get(gh_url)
text = b64decode(json.loads(r.text)['content'])

with open(hook_path,'w') as f:
    f.write(text)
